import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          KloudWranglers Blog
        </h1>
        <nav>
          <Link href="/static">
            Statically Rendered Site
          </Link>
          &nbsp;/&nbsp;
          <Link href="/dynamic">
            Server Side Rendered Site
          </Link>
        </nav>
      </main>
    </div>
  )
}
